// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6DiYTfd45vlMInGIy7aSbiwhh6gpaFM',
    appId: '1:473726195771:web:4f24bf53a8be44ee40641e',
    messagingSenderId: '473726195771',
    projectId: 'flashnews-56393',
    authDomain: 'flashnews-56393.firebaseapp.com',
    storageBucket: 'flashnews-56393.firebasestorage.app',
    measurementId: 'G-2HS1YW65EL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjP1afA6YzhFhQvJ7yYdycyzC6Shl5Izk',
    appId: '1:473726195771:android:c6e4e931c3c5cd0740641e',
    messagingSenderId: '473726195771',
    projectId: 'flashnews-56393',
    storageBucket: 'flashnews-56393.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAeShIGBEUGyFPpG0bfqAGpK8twzjE9JM',
    appId: '1:473726195771:ios:1748b1a9fab4c3ac40641e',
    messagingSenderId: '473726195771',
    projectId: 'flashnews-56393',
    storageBucket: 'flashnews-56393.firebasestorage.app',
    iosBundleId: 'com.flash.flashNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAeShIGBEUGyFPpG0bfqAGpK8twzjE9JM',
    appId: '1:473726195771:ios:1281d50e31e5b7b840641e',
    messagingSenderId: '473726195771',
    projectId: 'flashnews-56393',
    storageBucket: 'flashnews-56393.firebasestorage.app',
    iosBundleId: 'com.example.flashNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6DiYTfd45vlMInGIy7aSbiwhh6gpaFM',
    appId: '1:473726195771:web:dae28fb44a873aa140641e',
    messagingSenderId: '473726195771',
    projectId: 'flashnews-56393',
    authDomain: 'flashnews-56393.firebaseapp.com',
    storageBucket: 'flashnews-56393.firebasestorage.app',
    measurementId: 'G-7M17XP6L2J',
  );
}
